import { FunctionComponent } from "react";
import styles from "./SignUp.module.css";

const SignUp: FunctionComponent = () => {
  return (
    <div className={styles.homepageInner}>
      <div className={styles.frameParent}>
        <div className={styles.wezboDoddle1Wrapper}>
          <div className={styles.wezboDoddle1}>
            <img className={styles.vectorIcon} alt="" src="../vector1.svg" />
            <img className={styles.vectorIcon1} alt="" src="../vector2.svg" />
            <img className={styles.vectorIcon2} alt="" src="../vector3.svg" />
            <img className={styles.vectorIcon3} alt="" src="../vector4.svg" />
            <img className={styles.vectorIcon4} alt="" src="../vector5.svg" />
            <img className={styles.vectorIcon5} alt="" src="../vector6.svg" />
            <img className={styles.vectorIcon6} alt="" src="../vector7.svg" />
            <img className={styles.vectorIcon7} alt="" src="../vector8.svg" />
            <img className={styles.vectorIcon8} alt="" src="../vector9.svg" />
            <img className={styles.vectorIcon9} alt="" src="../vector10.svg" />
            <img className={styles.vectorIcon10} alt="" src="../vector11.svg" />
            <img className={styles.vectorIcon11} alt="" src="../vector12.svg" />
            <img className={styles.vectorIcon12} alt="" src="../vector13.svg" />
            <img className={styles.vectorIcon13} alt="" src="../vector14.svg" />
            <img className={styles.vectorIcon14} alt="" src="../vector15.svg" />
            <img className={styles.vectorIcon15} alt="" src="../vector16.svg" />
            <img className={styles.vectorIcon16} alt="" src="../vector17.svg" />
            <img className={styles.vectorIcon17} alt="" src="../vector18.svg" />
            <img className={styles.vectorIcon18} alt="" src="../vector19.svg" />
            <img className={styles.vectorIcon19} alt="" src="../vector20.svg" />
            <img className={styles.vectorIcon20} alt="" src="../vector21.svg" />
            <img className={styles.vectorIcon21} alt="" src="../vector22.svg" />
            <img className={styles.vectorIcon22} alt="" src="../vector23.svg" />
            <img className={styles.vectorIcon23} alt="" src="../vector24.svg" />
            <img className={styles.vectorIcon24} alt="" src="../vector25.svg" />
            <img className={styles.vectorIcon25} alt="" src="../vector26.svg" />
            <img className={styles.vectorIcon26} alt="" src="../vector27.svg" />
            <img className={styles.vectorIcon27} alt="" src="../vector28.svg" />
            <img className={styles.vectorIcon28} alt="" src="../vector29.svg" />
            <img className={styles.vectorIcon29} alt="" src="../vector30.svg" />
            <img className={styles.vectorIcon30} alt="" src="../vector31.svg" />
            <img className={styles.vectorIcon31} alt="" src="../vector32.svg" />
            <img className={styles.vectorIcon32} alt="" src="../vector33.svg" />
            <img className={styles.vectorIcon33} alt="" src="../vector34.svg" />
            <img className={styles.vectorIcon34} alt="" src="../vector35.svg" />
            <img className={styles.vectorIcon35} alt="" src="../vector36.svg" />
            <img className={styles.vectorIcon36} alt="" src="../vector37.svg" />
            <img className={styles.vectorIcon37} alt="" src="../vector38.svg" />
            <img className={styles.vectorIcon38} alt="" src="../vector39.svg" />
            <img className={styles.vectorIcon39} alt="" src="../vector40.svg" />
            <img className={styles.vectorIcon40} alt="" src="../vector41.svg" />
            <img className={styles.vectorIcon41} alt="" src="../vector42.svg" />
            <img className={styles.vectorIcon42} alt="" src="../vector43.svg" />
            <img className={styles.vectorIcon43} alt="" src="../vector44.svg" />
            <img className={styles.vectorIcon44} alt="" src="../vector45.svg" />
            <img className={styles.vectorIcon45} alt="" src="../vector46.svg" />
            <img className={styles.vectorIcon46} alt="" src="../vector47.svg" />
            <img className={styles.vectorIcon47} alt="" src="../vector48.svg" />
            <img className={styles.vectorIcon48} alt="" src="../vector49.svg" />
            <img className={styles.vectorIcon49} alt="" src="../vector50.svg" />
            <img className={styles.vectorIcon50} alt="" src="../vector51.svg" />
            <img className={styles.vectorIcon51} alt="" src="../vector52.svg" />
            <img className={styles.vectorIcon52} alt="" src="../vector53.svg" />
            <img className={styles.vectorIcon53} alt="" src="../vector54.svg" />
            <img className={styles.vectorIcon54} alt="" src="../vector55.svg" />
            <img className={styles.vectorIcon55} alt="" src="../vector56.svg" />
            <img className={styles.vectorIcon56} alt="" src="../vector57.svg" />
            <img className={styles.vectorIcon57} alt="" src="../vector58.svg" />
            <img className={styles.vectorIcon58} alt="" src="../vector59.svg" />
            <img className={styles.vectorIcon59} alt="" src="../vector60.svg" />
            <img className={styles.vectorIcon60} alt="" src="../vector61.svg" />
            <img className={styles.vectorIcon61} alt="" src="../vector62.svg" />
            <img className={styles.vectorIcon62} alt="" src="../vector63.svg" />
            <img className={styles.vectorIcon63} alt="" />
            <img className={styles.vectorIcon64} alt="" src="../vector64.svg" />
            <img className={styles.vectorIcon65} alt="" src="../vector65.svg" />
            <img className={styles.vectorIcon66} alt="" src="../vector66.svg" />
            <img className={styles.vectorIcon67} alt="" />
            <img className={styles.vectorIcon68} alt="" src="../vector67.svg" />
            <img className={styles.vectorIcon69} alt="" src="../vector68.svg" />
            <img className={styles.vectorIcon70} alt="" src="../vector69.svg" />
            <img className={styles.vectorIcon71} alt="" src="../vector70.svg" />
            <img className={styles.vectorIcon72} alt="" src="../vector71.svg" />
            <img className={styles.vectorIcon73} alt="" src="../vector72.svg" />
            <img className={styles.vectorIcon74} alt="" src="../vector73.svg" />
            <img className={styles.vectorIcon75} alt="" src="../vector74.svg" />
            <img className={styles.vectorIcon76} alt="" />
            <img className={styles.vectorIcon77} alt="" src="../vector75.svg" />
            <img className={styles.vectorIcon78} alt="" src="../vector76.svg" />
            <img className={styles.vectorIcon79} alt="" src="../vector77.svg" />
            <img className={styles.vectorIcon80} alt="" src="../vector78.svg" />
            <img className={styles.vectorIcon81} alt="" src="../vector79.svg" />
            <img className={styles.vectorIcon82} alt="" src="../vector80.svg" />
            <img className={styles.vectorIcon83} alt="" src="../vector81.svg" />
            <img className={styles.vectorIcon84} alt="" src="../vector82.svg" />
            <img className={styles.vectorIcon85} alt="" src="../vector83.svg" />
            <img className={styles.vectorIcon86} alt="" src="../vector84.svg" />
            <img className={styles.vectorIcon87} alt="" src="../vector85.svg" />
            <img className={styles.vectorIcon88} alt="" src="../vector86.svg" />
            <img className={styles.vectorIcon89} alt="" src="../vector87.svg" />
            <img className={styles.vectorIcon90} alt="" src="../vector88.svg" />
            <img className={styles.vectorIcon91} alt="" src="../vector89.svg" />
            <img className={styles.vectorIcon92} alt="" src="../vector90.svg" />
            <img className={styles.vectorIcon93} alt="" src="../vector91.svg" />
            <img className={styles.vectorIcon94} alt="" src="../vector92.svg" />
            <img className={styles.vectorIcon95} alt="" src="../vector93.svg" />
            <img className={styles.vectorIcon96} alt="" src="../vector94.svg" />
            <img className={styles.vectorIcon97} alt="" src="../vector95.svg" />
            <img className={styles.vectorIcon98} alt="" src="../vector96.svg" />
            <img className={styles.vectorIcon99} alt="" src="../vector97.svg" />
            <img
              className={styles.vectorIcon100}
              alt=""
              src="../vector98.svg"
            />
            <img
              className={styles.vectorIcon101}
              alt=""
              src="../vector99.svg"
            />
            <img
              className={styles.vectorIcon102}
              alt=""
              src="../vector100.svg"
            />
            <img
              className={styles.vectorIcon103}
              alt=""
              src="../vector101.svg"
            />
            <img
              className={styles.vectorIcon104}
              alt=""
              src="../vector102.svg"
            />
            <img
              className={styles.vectorIcon105}
              alt=""
              src="../vector103.svg"
            />
            <img
              className={styles.vectorIcon106}
              alt=""
              src="../vector104.svg"
            />
            <img
              className={styles.vectorIcon107}
              alt=""
              src="../vector105.svg"
            />
            <img
              className={styles.vectorIcon108}
              alt=""
              src="../vector106.svg"
            />
            <img
              className={styles.vectorIcon109}
              alt=""
              src="../vector107.svg"
            />
            <img
              className={styles.vectorIcon110}
              alt=""
              src="../vector108.svg"
            />
            <img
              className={styles.vectorIcon111}
              alt=""
              src="../vector109.svg"
            />
            <img
              className={styles.vectorIcon112}
              alt=""
              src="../vector110.svg"
            />
            <img
              className={styles.vectorIcon113}
              alt=""
              src="../vector111.svg"
            />
            <img
              className={styles.vectorIcon114}
              alt=""
              src="../vector112.svg"
            />
            <img className={styles.vectorIcon115} alt="" />
            <img
              className={styles.vectorIcon116}
              alt=""
              src="../vector113.svg"
            />
            <img
              className={styles.vectorIcon117}
              alt=""
              src="../vector114.svg"
            />
            <img
              className={styles.vectorIcon118}
              alt=""
              src="../vector115.svg"
            />
            <img
              className={styles.vectorIcon119}
              alt=""
              src="../vector116.svg"
            />
            <img
              className={styles.vectorIcon120}
              alt=""
              src="../vector117.svg"
            />
            <img className={styles.vectorIcon121} alt="" />
            <img
              className={styles.vectorIcon122}
              alt=""
              src="../vector118.svg"
            />
            <img className={styles.vectorIcon123} alt="" />
            <img
              className={styles.vectorIcon124}
              alt=""
              src="../vector119.svg"
            />
            <img
              className={styles.vectorIcon125}
              alt=""
              src="../vector120.svg"
            />
            <img
              className={styles.vectorIcon126}
              alt=""
              src="../vector121.svg"
            />
            <img
              className={styles.vectorIcon127}
              alt=""
              src="../vector122.svg"
            />
            <img
              className={styles.vectorIcon128}
              alt=""
              src="../vector123.svg"
            />
            <img
              className={styles.vectorIcon129}
              alt=""
              src="../vector124.svg"
            />
            <img
              className={styles.vectorIcon130}
              alt=""
              src="../vector125.svg"
            />
            <img
              className={styles.vectorIcon131}
              alt=""
              src="../vector126.svg"
            />
            <img className={styles.vectorIcon132} alt="" />
            <img
              className={styles.vectorIcon133}
              alt=""
              src="../vector127.svg"
            />
            <img
              className={styles.vectorIcon134}
              alt=""
              src="../vector128.svg"
            />
            <img className={styles.vectorIcon135} alt="" />
            <img
              className={styles.vectorIcon136}
              alt=""
              src="../vector129.svg"
            />
            <img
              className={styles.vectorIcon137}
              alt=""
              src="../vector130.svg"
            />
            <img className={styles.vectorIcon76} alt="" />
            <img
              className={styles.vectorIcon139}
              alt=""
              src="../vector131.svg"
            />
            <img
              className={styles.vectorIcon140}
              alt=""
              src="../vector132.svg"
            />
            <img
              className={styles.vectorIcon141}
              alt=""
              src="../vector133.svg"
            />
            <img className={styles.vectorIcon142} alt="" />
            <img
              className={styles.vectorIcon143}
              alt=""
              src="../vector134.svg"
            />
            <img
              className={styles.vectorIcon144}
              alt=""
              src="../vector135.svg"
            />
            <img
              className={styles.vectorIcon145}
              alt=""
              src="../vector136.svg"
            />
            <img
              className={styles.vectorIcon146}
              alt=""
              src="../vector137.svg"
            />
            <img className={styles.vectorIcon147} alt="" />
            <img
              className={styles.vectorIcon148}
              alt=""
              src="../vector138.svg"
            />
            <img
              className={styles.vectorIcon149}
              alt=""
              src="../vector139.svg"
            />
            <img
              className={styles.vectorIcon150}
              alt=""
              src="../vector140.svg"
            />
            <img
              className={styles.vectorIcon151}
              alt=""
              src="../vector141.svg"
            />
            <img
              className={styles.vectorIcon152}
              alt=""
              src="../vector142.svg"
            />
            <img
              className={styles.vectorIcon153}
              alt=""
              src="../vector143.svg"
            />
            <img
              className={styles.vectorIcon154}
              alt=""
              src="../vector144.svg"
            />
            <img
              className={styles.vectorIcon155}
              alt=""
              src="../vector145.svg"
            />
            <img
              className={styles.vectorIcon156}
              alt=""
              src="../vector146.svg"
            />
            <img
              className={styles.vectorIcon157}
              alt=""
              src="../vector147.svg"
            />
            <img
              className={styles.vectorIcon158}
              alt=""
              src="../vector148.svg"
            />
            <img
              className={styles.vectorIcon159}
              alt=""
              src="../vector149.svg"
            />
            <img
              className={styles.vectorIcon160}
              alt=""
              src="../vector150.svg"
            />
            <img
              className={styles.vectorIcon161}
              alt=""
              src="../vector151.svg"
            />
            <img
              className={styles.vectorIcon162}
              alt=""
              src="../vector152.svg"
            />
            <img
              className={styles.vectorIcon163}
              alt=""
              src="../vector153.svg"
            />
            <img
              className={styles.vectorIcon164}
              alt=""
              src="../vector154.svg"
            />
            <img
              className={styles.vectorIcon165}
              alt=""
              src="../vector155.svg"
            />
            <img
              className={styles.vectorIcon166}
              alt=""
              src="../vector156.svg"
            />
            <img
              className={styles.vectorIcon167}
              alt=""
              src="../vector157.svg"
            />
            <img
              className={styles.vectorIcon168}
              alt=""
              src="../vector158.svg"
            />
            <img
              className={styles.vectorIcon169}
              alt=""
              src="../vector159.svg"
            />
            <img
              className={styles.vectorIcon170}
              alt=""
              src="../vector160.svg"
            />
            <img
              className={styles.vectorIcon171}
              alt=""
              src="../vector161.svg"
            />
            <img
              className={styles.vectorIcon172}
              alt=""
              src="../vector162.svg"
            />
            <img
              className={styles.vectorIcon173}
              alt=""
              src="../vector163.svg"
            />
            <img
              className={styles.vectorIcon174}
              alt=""
              src="../vector164.svg"
            />
            <img
              className={styles.vectorIcon175}
              alt=""
              src="../vector165.svg"
            />
            <img
              className={styles.vectorIcon176}
              alt=""
              src="../vector166.svg"
            />
            <img
              className={styles.vectorIcon177}
              alt=""
              src="../vector167.svg"
            />
            <img
              className={styles.vectorIcon178}
              alt=""
              src="../vector168.svg"
            />
            <img
              className={styles.vectorIcon179}
              alt=""
              src="../vector169.svg"
            />
            <img
              className={styles.vectorIcon180}
              alt=""
              src="../vector170.svg"
            />
            <img
              className={styles.vectorIcon181}
              alt=""
              src="../vector171.svg"
            />
            <img
              className={styles.vectorIcon182}
              alt=""
              src="../vector172.svg"
            />
            <img
              className={styles.vectorIcon183}
              alt=""
              src="../vector173.svg"
            />
            <img
              className={styles.vectorIcon184}
              alt=""
              src="../vector174.svg"
            />
            <img
              className={styles.vectorIcon185}
              alt=""
              src="../vector175.svg"
            />
            <img
              className={styles.vectorIcon186}
              alt=""
              src="../vector176.svg"
            />
            <img
              className={styles.vectorIcon187}
              alt=""
              src="../vector177.svg"
            />
            <img
              className={styles.vectorIcon188}
              alt=""
              src="../vector178.svg"
            />
            <img
              className={styles.vectorIcon189}
              alt=""
              src="../vector179.svg"
            />
            <img
              className={styles.vectorIcon190}
              alt=""
              src="../vector180.svg"
            />
            <img
              className={styles.vectorIcon191}
              alt=""
              src="../vector181.svg"
            />
            <img
              className={styles.vectorIcon192}
              alt=""
              src="../vector182.svg"
            />
            <img
              className={styles.vectorIcon193}
              alt=""
              src="../vector183.svg"
            />
            <img
              className={styles.vectorIcon194}
              alt=""
              src="../vector184.svg"
            />
            <img
              className={styles.vectorIcon195}
              alt=""
              src="../vector185.svg"
            />
            <img
              className={styles.vectorIcon196}
              alt=""
              src="../vector186.svg"
            />
            <img
              className={styles.vectorIcon197}
              alt=""
              src="../vector187.svg"
            />
            <img
              className={styles.vectorIcon198}
              alt=""
              src="../vector188.svg"
            />
            <img
              className={styles.vectorIcon199}
              alt=""
              src="../vector189.svg"
            />
            <img
              className={styles.vectorIcon200}
              alt=""
              src="../vector190.svg"
            />
            <img
              className={styles.vectorIcon201}
              alt=""
              src="../vector191.svg"
            />
            <img
              className={styles.vectorIcon202}
              alt=""
              src="../vector192.svg"
            />
            <img
              className={styles.vectorIcon203}
              alt=""
              src="../vector193.svg"
            />
            <img
              className={styles.vectorIcon204}
              alt=""
              src="../vector194.svg"
            />
            <img
              className={styles.vectorIcon205}
              alt=""
              src="../vector195.svg"
            />
            <img
              className={styles.vectorIcon206}
              alt=""
              src="../vector196.svg"
            />
            <img className={styles.vectorIcon207} alt="" />
            <img
              className={styles.vectorIcon208}
              alt=""
              src="../vector197.svg"
            />
            <img
              className={styles.vectorIcon209}
              alt=""
              src="../vector198.svg"
            />
            <img
              className={styles.vectorIcon210}
              alt=""
              src="../vector199.svg"
            />
            <img
              className={styles.vectorIcon211}
              alt=""
              src="../vector200.svg"
            />
            <img className={styles.vectorIcon212} alt="" />
            <img
              className={styles.vectorIcon213}
              alt=""
              src="../vector201.svg"
            />
            <img
              className={styles.vectorIcon214}
              alt=""
              src="../vector202.svg"
            />
            <img
              className={styles.vectorIcon215}
              alt=""
              src="../vector203.svg"
            />
            <img
              className={styles.vectorIcon216}
              alt=""
              src="../vector204.svg"
            />
            <img
              className={styles.vectorIcon217}
              alt=""
              src="../vector205.svg"
            />
            <img className={styles.vectorIcon218} alt="" />
            <img
              className={styles.vectorIcon219}
              alt=""
              src="../vector206.svg"
            />
            <img
              className={styles.vectorIcon220}
              alt=""
              src="../vector207.svg"
            />
            <img
              className={styles.vectorIcon221}
              alt=""
              src="../vector208.svg"
            />
            <img
              className={styles.vectorIcon222}
              alt=""
              src="../vector209.svg"
            />
            <img
              className={styles.vectorIcon223}
              alt=""
              src="../vector210.svg"
            />
            <img
              className={styles.vectorIcon224}
              alt=""
              src="../vector211.svg"
            />
            <img
              className={styles.vectorIcon225}
              alt=""
              src="../vector212.svg"
            />
            <img
              className={styles.vectorIcon226}
              alt=""
              src="../vector213.svg"
            />
            <img
              className={styles.vectorIcon227}
              alt=""
              src="../vector214.svg"
            />
            <img
              className={styles.vectorIcon228}
              alt=""
              src="../vector215.svg"
            />
            <img
              className={styles.vectorIcon229}
              alt=""
              src="../vector216.svg"
            />
            <img
              className={styles.vectorIcon230}
              alt=""
              src="../vector217.svg"
            />
            <img
              className={styles.vectorIcon231}
              alt=""
              src="../vector218.svg"
            />
            <img
              className={styles.vectorIcon232}
              alt=""
              src="../vector219.svg"
            />
            <img
              className={styles.vectorIcon233}
              alt=""
              src="../vector220.svg"
            />
            <img
              className={styles.vectorIcon234}
              alt=""
              src="../vector221.svg"
            />
            <img
              className={styles.vectorIcon235}
              alt=""
              src="../vector222.svg"
            />
            <img
              className={styles.vectorIcon236}
              alt=""
              src="../vector223.svg"
            />
            <img
              className={styles.vectorIcon237}
              alt=""
              src="../vector224.svg"
            />
            <img
              className={styles.vectorIcon238}
              alt=""
              src="../vector225.svg"
            />
            <img
              className={styles.vectorIcon239}
              alt=""
              src="../vector226.svg"
            />
            <img
              className={styles.vectorIcon240}
              alt=""
              src="../vector227.svg"
            />
            <img
              className={styles.vectorIcon241}
              alt=""
              src="../vector228.svg"
            />
            <img
              className={styles.vectorIcon242}
              alt=""
              src="../vector229.svg"
            />
            <img
              className={styles.vectorIcon243}
              alt=""
              src="../vector230.svg"
            />
            <img
              className={styles.vectorIcon244}
              alt=""
              src="../vector231.svg"
            />
            <img
              className={styles.vectorIcon245}
              alt=""
              src="../vector232.svg"
            />
            <img
              className={styles.vectorIcon246}
              alt=""
              src="../vector233.svg"
            />
            <img className={styles.vectorIcon247} alt="" />
            <img
              className={styles.vectorIcon248}
              alt=""
              src="../vector234.svg"
            />
            <img
              className={styles.vectorIcon249}
              alt=""
              src="../vector235.svg"
            />
            <img
              className={styles.vectorIcon250}
              alt=""
              src="../vector236.svg"
            />
            <img
              className={styles.vectorIcon251}
              alt=""
              src="../vector237.svg"
            />
            <img
              className={styles.vectorIcon252}
              alt=""
              src="../vector238.svg"
            />
            <img
              className={styles.vectorIcon253}
              alt=""
              src="../vector239.svg"
            />
            <img
              className={styles.vectorIcon254}
              alt=""
              src="../vector240.svg"
            />
            <img
              className={styles.vectorIcon255}
              alt=""
              src="../vector241.svg"
            />
            <img
              className={styles.vectorIcon256}
              alt=""
              src="../vector242.svg"
            />
            <img
              className={styles.vectorIcon257}
              alt=""
              src="../vector243.svg"
            />
            <img
              className={styles.vectorIcon258}
              alt=""
              src="../vector244.svg"
            />
            <img
              className={styles.vectorIcon259}
              alt=""
              src="../vector245.svg"
            />
            <img
              className={styles.vectorIcon260}
              alt=""
              src="../vector246.svg"
            />
            <img
              className={styles.vectorIcon261}
              alt=""
              src="../vector247.svg"
            />
            <img
              className={styles.vectorIcon262}
              alt=""
              src="../vector248.svg"
            />
            <img
              className={styles.vectorIcon263}
              alt=""
              src="../vector249.svg"
            />
            <img className={styles.vectorIcon264} alt="" />
            <img
              className={styles.vectorIcon265}
              alt=""
              src="../vector250.svg"
            />
            <img
              className={styles.vectorIcon266}
              alt=""
              src="../vector251.svg"
            />
            <img
              className={styles.vectorIcon267}
              alt=""
              src="../vector252.svg"
            />
            <img
              className={styles.vectorIcon268}
              alt=""
              src="../vector253.svg"
            />
            <img
              className={styles.vectorIcon269}
              alt=""
              src="../vector254.svg"
            />
            <img
              className={styles.vectorIcon270}
              alt=""
              src="../vector255.svg"
            />
            <img className={styles.vectorIcon271} alt="" />
            <img
              className={styles.vectorIcon272}
              alt=""
              src="../vector256.svg"
            />
            <img
              className={styles.vectorIcon273}
              alt=""
              src="../vector257.svg"
            />
            <img
              className={styles.vectorIcon274}
              alt=""
              src="../vector258.svg"
            />
            <img
              className={styles.vectorIcon275}
              alt=""
              src="../vector259.svg"
            />
            <img
              className={styles.vectorIcon276}
              alt=""
              src="../vector260.svg"
            />
            <img
              className={styles.vectorIcon277}
              alt=""
              src="../vector261.svg"
            />
            <img
              className={styles.vectorIcon278}
              alt=""
              src="../vector262.svg"
            />
            <img
              className={styles.vectorIcon279}
              alt=""
              src="../vector263.svg"
            />
            <img
              className={styles.vectorIcon280}
              alt=""
              src="../vector264.svg"
            />
            <img
              className={styles.vectorIcon281}
              alt=""
              src="../vector265.svg"
            />
            <img
              className={styles.vectorIcon282}
              alt=""
              src="../vector266.svg"
            />
            <img
              className={styles.vectorIcon283}
              alt=""
              src="../vector267.svg"
            />
            <img
              className={styles.vectorIcon284}
              alt=""
              src="../vector268.svg"
            />
            <img
              className={styles.vectorIcon285}
              alt=""
              src="../vector269.svg"
            />
            <img
              className={styles.vectorIcon286}
              alt=""
              src="../vector270.svg"
            />
            <img
              className={styles.vectorIcon287}
              alt=""
              src="../vector271.svg"
            />
            <img
              className={styles.vectorIcon288}
              alt=""
              src="../vector272.svg"
            />
            <img
              className={styles.vectorIcon289}
              alt=""
              src="../vector273.svg"
            />
            <img
              className={styles.vectorIcon290}
              alt=""
              src="../vector274.svg"
            />
            <img
              className={styles.vectorIcon291}
              alt=""
              src="../vector275.svg"
            />
            <img
              className={styles.vectorIcon292}
              alt=""
              src="../vector276.svg"
            />
            <img
              className={styles.vectorIcon293}
              alt=""
              src="../vector277.svg"
            />
            <img
              className={styles.vectorIcon294}
              alt=""
              src="../vector278.svg"
            />
            <img
              className={styles.vectorIcon295}
              alt=""
              src="../vector279.svg"
            />
            <img
              className={styles.vectorIcon296}
              alt=""
              src="../vector280.svg"
            />
            <img
              className={styles.vectorIcon297}
              alt=""
              src="../vector281.svg"
            />
            <img
              className={styles.vectorIcon298}
              alt=""
              src="../vector282.svg"
            />
            <img
              className={styles.vectorIcon299}
              alt=""
              src="../vector283.svg"
            />
            <img
              className={styles.vectorIcon300}
              alt=""
              src="../vector284.svg"
            />
            <img
              className={styles.vectorIcon301}
              alt=""
              src="../vector285.svg"
            />
            <img
              className={styles.vectorIcon302}
              alt=""
              src="../vector286.svg"
            />
            <img
              className={styles.vectorIcon303}
              alt=""
              src="../vector287.svg"
            />
            <img
              className={styles.vectorIcon304}
              alt=""
              src="../vector288.svg"
            />
            <img
              className={styles.vectorIcon305}
              alt=""
              src="../vector289.svg"
            />
            <img
              className={styles.vectorIcon306}
              alt=""
              src="../vector290.svg"
            />
            <img
              className={styles.vectorIcon307}
              alt=""
              src="../vector291.svg"
            />
            <img
              className={styles.vectorIcon308}
              alt=""
              src="../vector292.svg"
            />
            <img
              className={styles.vectorIcon309}
              alt=""
              src="../vector293.svg"
            />
            <img
              className={styles.vectorIcon310}
              alt=""
              src="../vector294.svg"
            />
            <img
              className={styles.vectorIcon311}
              alt=""
              src="../vector295.svg"
            />
            <img
              className={styles.vectorIcon312}
              alt=""
              src="../vector296.svg"
            />
            <img
              className={styles.vectorIcon313}
              alt=""
              src="../vector297.svg"
            />
            <img
              className={styles.vectorIcon314}
              alt=""
              src="../vector298.svg"
            />
            <img
              className={styles.vectorIcon315}
              alt=""
              src="../vector299.svg"
            />
            <img
              className={styles.vectorIcon316}
              alt=""
              src="../vector300.svg"
            />
            <img
              className={styles.vectorIcon317}
              alt=""
              src="../vector301.svg"
            />
            <img
              className={styles.vectorIcon318}
              alt=""
              src="../vector302.svg"
            />
            <img
              className={styles.vectorIcon319}
              alt=""
              src="../vector303.svg"
            />
            <img
              className={styles.vectorIcon320}
              alt=""
              src="../vector304.svg"
            />
            <img
              className={styles.vectorIcon321}
              alt=""
              src="../vector305.svg"
            />
            <img className={styles.vectorIcon322} alt="" />
            <img
              className={styles.vectorIcon323}
              alt=""
              src="../vector306.svg"
            />
            <img
              className={styles.vectorIcon324}
              alt=""
              src="../vector307.svg"
            />
            <img
              className={styles.vectorIcon325}
              alt=""
              src="../vector308.svg"
            />
            <img
              className={styles.vectorIcon326}
              alt=""
              src="../vector309.svg"
            />
            <img
              className={styles.vectorIcon327}
              alt=""
              src="../vector310.svg"
            />
            <img
              className={styles.vectorIcon328}
              alt=""
              src="../vector311.svg"
            />
            <img
              className={styles.vectorIcon329}
              alt=""
              src="../vector312.svg"
            />
            <img
              className={styles.vectorIcon330}
              alt=""
              src="../vector313.svg"
            />
            <img
              className={styles.vectorIcon331}
              alt=""
              src="../vector314.svg"
            />
            <img
              className={styles.vectorIcon332}
              alt=""
              src="../vector315.svg"
            />
            <img
              className={styles.vectorIcon333}
              alt=""
              src="../vector316.svg"
            />
            <img
              className={styles.vectorIcon334}
              alt=""
              src="../vector317.svg"
            />
            <img
              className={styles.vectorIcon335}
              alt=""
              src="../vector318.svg"
            />
            <img
              className={styles.vectorIcon336}
              alt=""
              src="../vector319.svg"
            />
            <img
              className={styles.vectorIcon337}
              alt=""
              src="../vector320.svg"
            />
            <img
              className={styles.vectorIcon338}
              alt=""
              src="../vector321.svg"
            />
            <img
              className={styles.vectorIcon339}
              alt=""
              src="../vector322.svg"
            />
            <img
              className={styles.vectorIcon340}
              alt=""
              src="../vector323.svg"
            />
            <img className={styles.vectorIcon341} alt="" />
            <img className={styles.vectorIcon342} alt="" />
            <img className={styles.vectorIcon343} alt="" />
            <img
              className={styles.vectorIcon344}
              alt=""
              src="../vector324.svg"
            />
            <img
              className={styles.vectorIcon345}
              alt=""
              src="../vector325.svg"
            />
            <img
              className={styles.vectorIcon346}
              alt=""
              src="../vector326.svg"
            />
            <img
              className={styles.vectorIcon347}
              alt=""
              src="../vector327.svg"
            />
            <img
              className={styles.vectorIcon348}
              alt=""
              src="../vector328.svg"
            />
            <img
              className={styles.vectorIcon349}
              alt=""
              src="../vector329.svg"
            />
            <img
              className={styles.vectorIcon350}
              alt=""
              src="../vector330.svg"
            />
            <img
              className={styles.vectorIcon351}
              alt=""
              src="../vector331.svg"
            />
            <img
              className={styles.vectorIcon352}
              alt=""
              src="../vector332.svg"
            />
            <img
              className={styles.vectorIcon353}
              alt=""
              src="../vector333.svg"
            />
            <img
              className={styles.vectorIcon354}
              alt=""
              src="../vector334.svg"
            />
            <img
              className={styles.vectorIcon355}
              alt=""
              src="../vector335.svg"
            />
            <img
              className={styles.vectorIcon356}
              alt=""
              src="../vector336.svg"
            />
            <img
              className={styles.vectorIcon357}
              alt=""
              src="../vector337.svg"
            />
            <img
              className={styles.vectorIcon358}
              alt=""
              src="../vector338.svg"
            />
            <img
              className={styles.vectorIcon359}
              alt=""
              src="../vector339.svg"
            />
            <img
              className={styles.vectorIcon360}
              alt=""
              src="../vector340.svg"
            />
            <img
              className={styles.vectorIcon361}
              alt=""
              src="../vector341.svg"
            />
            <img
              className={styles.vectorIcon362}
              alt=""
              src="../vector342.svg"
            />
            <img
              className={styles.vectorIcon363}
              alt=""
              src="../vector343.svg"
            />
            <img
              className={styles.vectorIcon364}
              alt=""
              src="../vector344.svg"
            />
            <img
              className={styles.vectorIcon365}
              alt=""
              src="../vector345.svg"
            />
            <img
              className={styles.vectorIcon366}
              alt=""
              src="../vector346.svg"
            />
            <img
              className={styles.vectorIcon367}
              alt=""
              src="../vector347.svg"
            />
            <img
              className={styles.vectorIcon368}
              alt=""
              src="../vector348.svg"
            />
            <img
              className={styles.vectorIcon369}
              alt=""
              src="../vector349.svg"
            />
            <img
              className={styles.vectorIcon370}
              alt=""
              src="../vector350.svg"
            />
            <img
              className={styles.vectorIcon371}
              alt=""
              src="../vector351.svg"
            />
            <img
              className={styles.vectorIcon372}
              alt=""
              src="../vector352.svg"
            />
            <img
              className={styles.vectorIcon373}
              alt=""
              src="../vector353.svg"
            />
            <img
              className={styles.vectorIcon374}
              alt=""
              src="../vector354.svg"
            />
            <img
              className={styles.vectorIcon375}
              alt=""
              src="../vector355.svg"
            />
            <img
              className={styles.vectorIcon376}
              alt=""
              src="../vector356.svg"
            />
            <img
              className={styles.vectorIcon377}
              alt=""
              src="../vector357.svg"
            />
            <img
              className={styles.vectorIcon378}
              alt=""
              src="../vector358.svg"
            />
            <img className={styles.vectorIcon379} alt="" />
            <img
              className={styles.vectorIcon380}
              alt=""
              src="../vector359.svg"
            />
            <img className={styles.vectorIcon381} alt="" />
            <img
              className={styles.vectorIcon382}
              alt=""
              src="../vector360.svg"
            />
            <img
              className={styles.vectorIcon383}
              alt=""
              src="../vector361.svg"
            />
            <img
              className={styles.vectorIcon384}
              alt=""
              src="../vector362.svg"
            />
            <img
              className={styles.vectorIcon385}
              alt=""
              src="../vector363.svg"
            />
            <img
              className={styles.vectorIcon386}
              alt=""
              src="../vector364.svg"
            />
            <img
              className={styles.vectorIcon387}
              alt=""
              src="../vector365.svg"
            />
            <img
              className={styles.vectorIcon388}
              alt=""
              src="../vector366.svg"
            />
            <img
              className={styles.vectorIcon389}
              alt=""
              src="../vector367.svg"
            />
            <img
              className={styles.vectorIcon390}
              alt=""
              src="../vector368.svg"
            />
            <img
              className={styles.vectorIcon391}
              alt=""
              src="../vector369.svg"
            />
            <img
              className={styles.vectorIcon392}
              alt=""
              src="../vector370.svg"
            />
            <img
              className={styles.vectorIcon393}
              alt=""
              src="../vector371.svg"
            />
            <img
              className={styles.vectorIcon394}
              alt=""
              src="../vector372.svg"
            />
            <img
              className={styles.vectorIcon395}
              alt=""
              src="../vector373.svg"
            />
            <img
              className={styles.vectorIcon396}
              alt=""
              src="../vector374.svg"
            />
            <img
              className={styles.vectorIcon397}
              alt=""
              src="../vector375.svg"
            />
            <img
              className={styles.vectorIcon398}
              alt=""
              src="../vector376.svg"
            />
            <img
              className={styles.vectorIcon399}
              alt=""
              src="../vector377.svg"
            />
            <img
              className={styles.vectorIcon400}
              alt=""
              src="../vector378.svg"
            />
            <img
              className={styles.vectorIcon401}
              alt=""
              src="../vector379.svg"
            />
            <img className={styles.vectorIcon402} alt="" />
            <img
              className={styles.vectorIcon403}
              alt=""
              src="../vector380.svg"
            />
            <img
              className={styles.vectorIcon404}
              alt=""
              src="../vector381.svg"
            />
            <img
              className={styles.vectorIcon405}
              alt=""
              src="../vector382.svg"
            />
            <img
              className={styles.vectorIcon406}
              alt=""
              src="../vector383.svg"
            />
            <img
              className={styles.vectorIcon407}
              alt=""
              src="../vector384.svg"
            />
            <img
              className={styles.vectorIcon408}
              alt=""
              src="../vector385.svg"
            />
            <img className={styles.vectorIcon409} alt="" />
            <img
              className={styles.vectorIcon410}
              alt=""
              src="../vector386.svg"
            />
            <img
              className={styles.vectorIcon411}
              alt=""
              src="../vector387.svg"
            />
            <img
              className={styles.vectorIcon412}
              alt=""
              src="../vector388.svg"
            />
            <img
              className={styles.vectorIcon413}
              alt=""
              src="../vector389.svg"
            />
            <img
              className={styles.vectorIcon414}
              alt=""
              src="../vector390.svg"
            />
            <img
              className={styles.vectorIcon415}
              alt=""
              src="../vector391.svg"
            />
            <img className={styles.vectorIcon416} alt="" />
            <img
              className={styles.vectorIcon417}
              alt=""
              src="../vector392.svg"
            />
            <img
              className={styles.vectorIcon418}
              alt=""
              src="../vector393.svg"
            />
            <img
              className={styles.vectorIcon419}
              alt=""
              src="../vector394.svg"
            />
            <img className={styles.vectorIcon420} alt="" />
            <img
              className={styles.vectorIcon421}
              alt=""
              src="../vector395.svg"
            />
            <img
              className={styles.vectorIcon422}
              alt=""
              src="../vector396.svg"
            />
            <img
              className={styles.vectorIcon423}
              alt=""
              src="../vector397.svg"
            />
            <img
              className={styles.vectorIcon424}
              alt=""
              src="../vector398.svg"
            />
            <img
              className={styles.vectorIcon425}
              alt=""
              src="../vector399.svg"
            />
            <img
              className={styles.vectorIcon426}
              alt=""
              src="../vector400.svg"
            />
            <img
              className={styles.vectorIcon427}
              alt=""
              src="../vector401.svg"
            />
            <img
              className={styles.vectorIcon428}
              alt=""
              src="../vector402.svg"
            />
            <img
              className={styles.vectorIcon429}
              alt=""
              src="../vector403.svg"
            />
            <img
              className={styles.vectorIcon430}
              alt=""
              src="../vector404.svg"
            />
            <img
              className={styles.vectorIcon431}
              alt=""
              src="../vector405.svg"
            />
            <img
              className={styles.vectorIcon432}
              alt=""
              src="../vector406.svg"
            />
            <img
              className={styles.vectorIcon433}
              alt=""
              src="../vector407.svg"
            />
            <img
              className={styles.vectorIcon434}
              alt=""
              src="../vector408.svg"
            />
            <img
              className={styles.vectorIcon435}
              alt=""
              src="../vector409.svg"
            />
            <img
              className={styles.vectorIcon436}
              alt=""
              src="../vector410.svg"
            />
            <img
              className={styles.vectorIcon437}
              alt=""
              src="../vector411.svg"
            />
            <img
              className={styles.vectorIcon438}
              alt=""
              src="../vector412.svg"
            />
            <img
              className={styles.vectorIcon439}
              alt=""
              src="../vector413.svg"
            />
            <img
              className={styles.vectorIcon440}
              alt=""
              src="../vector414.svg"
            />
            <img
              className={styles.vectorIcon441}
              alt=""
              src="../vector415.svg"
            />
            <img
              className={styles.vectorIcon442}
              alt=""
              src="../vector416.svg"
            />
            <img
              className={styles.vectorIcon443}
              alt=""
              src="../vector417.svg"
            />
            <img
              className={styles.vectorIcon444}
              alt=""
              src="../vector418.svg"
            />
            <img
              className={styles.vectorIcon445}
              alt=""
              src="../vector419.svg"
            />
            <img
              className={styles.vectorIcon446}
              alt=""
              src="../vector420.svg"
            />
            <img
              className={styles.vectorIcon447}
              alt=""
              src="../vector421.svg"
            />
            <img
              className={styles.vectorIcon448}
              alt=""
              src="../vector422.svg"
            />
            <img
              className={styles.vectorIcon449}
              alt=""
              src="../vector423.svg"
            />
            <img
              className={styles.vectorIcon450}
              alt=""
              src="../vector424.svg"
            />
            <img
              className={styles.vectorIcon451}
              alt=""
              src="../vector425.svg"
            />
            <img
              className={styles.vectorIcon452}
              alt=""
              src="../vector426.svg"
            />
            <img
              className={styles.vectorIcon453}
              alt=""
              src="../vector427.svg"
            />
            <img
              className={styles.vectorIcon454}
              alt=""
              src="../vector428.svg"
            />
            <img
              className={styles.vectorIcon455}
              alt=""
              src="../vector429.svg"
            />
            <img
              className={styles.vectorIcon456}
              alt=""
              src="../vector430.svg"
            />
            <img
              className={styles.vectorIcon457}
              alt=""
              src="../vector431.svg"
            />
            <img
              className={styles.vectorIcon458}
              alt=""
              src="../vector432.svg"
            />
            <img
              className={styles.vectorIcon459}
              alt=""
              src="../vector433.svg"
            />
            <img
              className={styles.vectorIcon460}
              alt=""
              src="../vector434.svg"
            />
            <img
              className={styles.vectorIcon461}
              alt=""
              src="../vector435.svg"
            />
            <img
              className={styles.vectorIcon462}
              alt=""
              src="../vector436.svg"
            />
            <img
              className={styles.vectorIcon463}
              alt=""
              src="../vector437.svg"
            />
            <img
              className={styles.vectorIcon464}
              alt=""
              src="../vector438.svg"
            />
            <img
              className={styles.vectorIcon465}
              alt=""
              src="../vector439.svg"
            />
            <img
              className={styles.vectorIcon466}
              alt=""
              src="../vector440.svg"
            />
            <img
              className={styles.vectorIcon467}
              alt=""
              src="../vector441.svg"
            />
            <img
              className={styles.vectorIcon468}
              alt=""
              src="../vector442.svg"
            />
            <img
              className={styles.vectorIcon469}
              alt=""
              src="../vector443.svg"
            />
            <img
              className={styles.vectorIcon470}
              alt=""
              src="../vector444.svg"
            />
            <img
              className={styles.vectorIcon471}
              alt=""
              src="../vector445.svg"
            />
            <img
              className={styles.vectorIcon472}
              alt=""
              src="../vector446.svg"
            />
            <img
              className={styles.vectorIcon473}
              alt=""
              src="../vector447.svg"
            />
            <img
              className={styles.vectorIcon474}
              alt=""
              src="../vector448.svg"
            />
            <img
              className={styles.vectorIcon475}
              alt=""
              src="../vector449.svg"
            />
            <img
              className={styles.vectorIcon476}
              alt=""
              src="../vector450.svg"
            />
            <img
              className={styles.vectorIcon477}
              alt=""
              src="../vector451.svg"
            />
            <img
              className={styles.vectorIcon478}
              alt=""
              src="../vector452.svg"
            />
            <img
              className={styles.vectorIcon479}
              alt=""
              src="../vector453.svg"
            />
            <img
              className={styles.vectorIcon480}
              alt=""
              src="../vector454.svg"
            />
            <img
              className={styles.vectorIcon481}
              alt=""
              src="../vector455.svg"
            />
            <img
              className={styles.vectorIcon482}
              alt=""
              src="../vector456.svg"
            />
            <img
              className={styles.vectorIcon483}
              alt=""
              src="../vector457.svg"
            />
            <img
              className={styles.vectorIcon484}
              alt=""
              src="../vector458.svg"
            />
            <img
              className={styles.vectorIcon485}
              alt=""
              src="../vector459.svg"
            />
            <img
              className={styles.vectorIcon486}
              alt=""
              src="../vector460.svg"
            />
            <img
              className={styles.vectorIcon487}
              alt=""
              src="../vector461.svg"
            />
            <img
              className={styles.vectorIcon488}
              alt=""
              src="../vector462.svg"
            />
            <img
              className={styles.vectorIcon489}
              alt=""
              src="../vector463.svg"
            />
            <img
              className={styles.vectorIcon490}
              alt=""
              src="../vector464.svg"
            />
            <img
              className={styles.vectorIcon491}
              alt=""
              src="../vector465.svg"
            />
            <img
              className={styles.vectorIcon492}
              alt=""
              src="../vector466.svg"
            />
            <img
              className={styles.vectorIcon493}
              alt=""
              src="../vector467.svg"
            />
            <img
              className={styles.vectorIcon494}
              alt=""
              src="../vector468.svg"
            />
            <img
              className={styles.vectorIcon495}
              alt=""
              src="../vector469.svg"
            />
            <img className={styles.vectorIcon496} alt="" />
            <img
              className={styles.vectorIcon497}
              alt=""
              src="../vector470.svg"
            />
            <img
              className={styles.vectorIcon498}
              alt=""
              src="../vector471.svg"
            />
            <img
              className={styles.vectorIcon499}
              alt=""
              src="../vector472.svg"
            />
            <img
              className={styles.vectorIcon500}
              alt=""
              src="../vector473.svg"
            />
            <img
              className={styles.vectorIcon501}
              alt=""
              src="../vector474.svg"
            />
            <img
              className={styles.vectorIcon502}
              alt=""
              src="../vector475.svg"
            />
            <img
              className={styles.vectorIcon503}
              alt=""
              src="../vector476.svg"
            />
            <img className={styles.vectorIcon504} alt="" />
            <img
              className={styles.vectorIcon505}
              alt=""
              src="../vector477.svg"
            />
            <img
              className={styles.vectorIcon506}
              alt=""
              src="../vector478.svg"
            />
            <img
              className={styles.vectorIcon507}
              alt=""
              src="../vector479.svg"
            />
            <img
              className={styles.vectorIcon508}
              alt=""
              src="../vector480.svg"
            />
            <img
              className={styles.vectorIcon509}
              alt=""
              src="../vector481.svg"
            />
            <img className={styles.vectorIcon510} alt="" />
            <img className={styles.vectorIcon511} alt="" />
            <img
              className={styles.vectorIcon512}
              alt=""
              src="../vector482.svg"
            />
            <img
              className={styles.vectorIcon513}
              alt=""
              src="../vector483.svg"
            />
            <img
              className={styles.vectorIcon514}
              alt=""
              src="../vector484.svg"
            />
            <img
              className={styles.vectorIcon515}
              alt=""
              src="../vector485.svg"
            />
            <img
              className={styles.vectorIcon516}
              alt=""
              src="../vector486.svg"
            />
            <div className={styles.in}>.in</div>
            <div className={styles.eu}>.eu</div>
            <div className={styles.com}>.com</div>
            <img
              className={styles.vectorIcon517}
              alt=""
              src="../vector487.svg"
            />
          </div>
        </div>
        <div className={styles.robustWebsiteBuilderWithTh}>
          Robust Website Builder with the best tools to help grow your brand!
        </div>
        <div className={styles.groupParent}>
          <div className={styles.rectangleParent}>
            <div className={styles.groupChild} />
            <div className={styles.groupItem} />
            <div className={styles.groupInner} />
          </div>
          <b className={styles.signUpFreeToStartCreating}>
            Sign up free to start creating
          </b>
          <div className={styles.primaryButton1}>
            <div className={styles.explore}>Lets Wezbo</div>
          </div>
          <img className={styles.rocket1Icon} alt="" src="../rocket-1.svg" />
        </div>
      </div>
    </div>
  );
};

export default SignUp;
